### PR TITLE
Fix: Prevent user from hiding/unhinding apps if the configured hider is not available

### LINKED ISSUE #211: [BUG] App changes hide mode to 'disabled' when opened and Shizuku is not running
**Describe the bug / 问题描述**
 App changes hide mode to 'disabled' when opened and Shizuku is not running. Not sure if it's a Bug since I looked up in the code and it's explicity coded there, but IMHO it should not have this behaviour since Shizuku state can be changed when WiFi connection changes.

**To Reproduce / 复现步骤**
Steps to reproduce the behavior / 复现异常的步骤:
1. Set Amarok to use Shizuku
2. Disable Shizuku intentionally or by disabling WiFi connection
3. Open Amarok and click Ok in the alert dialog
4. Click Reveal nothing happens
5. Go to settings and check hide mode set to Disabled

**Expected behavior / 预期行为**
It should not change the default app hider, allowing me to fix the problem and then try again. Also, it should not allow clicking in the Reveal button if no app hider is enabled.

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: MIUI 13
 - Android Version / 安卓版本: 12
 - Amarok Version / Amarok版本: v0.9.3-foss

The code I mentioned is this:
```java
        // Check Hiders availability
        PrefMgr.getAppHider(this).tryToActivate((appHiderClass, succeed, msg) -> {
            if (succeed) return;
            PrefMgr.setAppHiderMode(NoneAppHider.class);
            new MaterialAlertDialogBuilder(this)
                    .setTitle(R.string.apphider_not_ava_title)
                    .setMessage(msg)
                    .setPositiveButton(R.string.switch_app_hider, (dialog, which)
                            -> startActivity(new Intent(this, SwitchAppHiderActivity.class)))
                    .setNegativeButton(getString(R.string.ok), null)
                    .show();
        });
```
https://github.com/deltazefiro/Amarok-Hider/blob/66661e23d7345a6e9d769969c002f68def7b3556/app/src/main/java/deltazero/amarok/ui/MainActivity.java#L82C13-L82C57

I can work on a fix, just want to confirm this is a bug first.

### PR DESCRIPTION
**Pull request by warleysr**
It creates a `isAvailable` method in all app hiders classes to check if the defined hider is ready to do it's job. Implements to check and allow toggle hide/unhide mode only if the app hider is available; if not, show the dialog to fix it. Also removes the default definition of app hider to `Disabled` when the previous one is not available, keeping the user defined one until the user itself changes it. 
- Fixes #211

### CODE REVIEW

**Review by deltazefiro — CHANGES_REQUESTED** [review]

File: app/src/main/java/deltazero/amarok/apphider/DsmAppHider.java [hunk 1]
```diff
@@ -72,4 +72,7 @@ public void tryToActivate(ActivationCallbackListener activationCallbackListener)
     public String getName() {
         return "DSM";
     }
+
+    @Override
+    public boolean isAvailable() { return !dpm.isAdminActive(admin); }
```
[the remark this answers is not in the document]
Comment (warleysr) [reply app/src/main/java/deltazero/amarok/apphider/DsmAppHider.java]: Way simpler indeed! Kept all the logic in `Hider` class, showing the same dialog on opening or clicking hide/reveal button. Tested with Shizuku and it works fine, would be great to test with other hiders.

File: app/src/main/java/deltazero/amarok/Hider.java [hunk 2]
```diff
@@ -53,6 +57,16 @@ public static State getState() {
     }
 
     public static void hide(Context context) {
+        PrefMgr.getAppHider(context).tryToActivate((appHiderClass, succeed, msg) -> {
+            if (succeed) {
+                processHide(context);
+                return;
+            }
+            showNoHiderDialog(context, msg);
```
Comment (deltazefiro) [inline app/src/main/java/deltazero/amarok/Hider.java:65]: If we hide from elsewhere expect the Amarok's main view, say the quick setting tile, this will cause a crash. Android disallow background processes to spawn dialogs. How about a toast message here?

**Review by deltazefiro — CHANGES_REQUESTED** [review]
I've tested with Dhizuku, Root and Shizuku. Works almost perfect!

File: app/src/main/java/deltazero/amarok/Hider.java (hunk 2 above)
Comment (warleysr) [reply app/src/main/java/deltazero/amarok/Hider.java:65]: Can I keep the dialog for actions triggered on app opening and main buttons click and the toast for the rest? The toast is a bit limited and doesn't guide the user to fix the issue.

Comment (deltazefiro) [reply app/src/main/java/deltazero/amarok/Hider.java:65]: Definitely! That'll be even better

**Comment by deltazefiro** [comment]
Thanks for your contribution
